### ISSUE TITLE
Make website indexable

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/nextgen-ui#9]
Current frontend is entirely unindexable.
The problem is mostly that Google (and other search engines) [don't index](https://www.quora.com/How-does-Google-index-the-URLs-of-a-single-page-with-the-hash-character-anchor-navigation-such-as-page-com-contact-or-page-com-gallery) hash navigation URLs. We need to devise a solution that would allow the frontend to be indexed by search engines. 

Options off the top of my head:
* Move to a server that allows for `pushState` navigation and generate actual links to token trading pages or produce a sitemap based on known tokens. Cons: requires moving away from GitHub Pages to some extent, requires a separate backend.
* Use [react-snapshot](https://github.com/geelen/react-snapshot), pre-render known token pages. Cons: refresh behaviour on custom tokens may differ from the known tokens.

**Comment by zaptrem** [comment]
Does react-snapshot run at build time before the push to the production environment?

**Comment by freeatnet** [comment]
@zaptrem Yeap, it's a build-time tool.

**Comment by JonathonDunford** [comment]
https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html

Google *says* they do it automatically.

Probably best to create a sitemap.xml with the hash urls.
Also, probably best to change the URLs to "hash bang" urls like so "forkdelta.com/#!/PPT-ETH"

**Comment by freeatnet** [comment]
Hash URLs are definitely not indexable. Hashbangs appear to be indexable [for the moment](https://twitter.com/JohnMu/status/834507305957855232). Maybe query string arguments would be a [better option still](https://www.seroundtable.com/google-no-url-fragments-23449.html).

**Comment by JonathonDunford** [comment]
After conversation in Discord and research. Google will phase out Hashbangs in summer of 2018.

Probably best to use a structure like so:

forkdelta.github.io/PPP-ETH

HOWEVER, github pages doesn't support .htaccess or index.php

We would need an .htaccess to redirect page requests to an index.php and index.php to handle sending the proper code to JS?

**Comment by JonathonDunford** [comment]
Short term, probably best to just use something like ?t=PPP-ETH

**Comment by zaptrem** [comment]
It’s probably best to avoid as much server side logic as possible to ease
future IPFS integration, so index.php redirects and push-state are not
advisable.

**Comment by JonathonDunford** [comment]
Then, the only real solution for google is using a query like ?t=PPP-ETH

**Comment by freeatnet** [comment]
No server-side _logic_ is required for pushstate support. The only thing needed is for the server at a given origin to serve the same HTML code regardless of the URL path. If that is not possible under IPFS, to options are acceptable:
1. We find a way to serve from IPFS with readable URLs, or
2. IPFS will be a secondary channel with a special config, while regular web version has readable URLs.

**Comment by JonathonDunford** [comment]
Update:

We have implemented a hashbang URL structure with push/popstate.

/#!/trade/PPP-ETH

We have also turned all of the pairs into links on the site to ease with Google indexing. We need a sitemap now.

**Comment by JonathonDunford** [comment]
Sitemap created and submitted.

**Comment by JonathonDunford** [comment]
711 web pages submitted to Google for indexing. :+1:
